[0m17:29:27.389456 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103acfc80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104555100>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104554e90>]}


============================== 17:29:27.391459 | 84241026-4468-4ccd-84cf-66f9171b5a2d ==============================
[0m17:29:27.391459 [info ] [MainThread]: Running with dbt=1.8.0
[0m17:29:27.391703 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/Users/shubhamnaik/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt init', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m17:29:30.995593 [debug] [MainThread]: Starter project path: /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/dbt/include/starter_project
[0m17:29:31.011691 [info ] [MainThread]: 
Your new dbt project "connection" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m17:29:31.012228 [info ] [MainThread]: Setting up your profile.
[0m17:30:45.132376 [info ] [MainThread]: Profile connection written to /Users/shubhamnaik/.dbt/profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m17:30:45.137978 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 77.78233, "process_user_time": 0.554697, "process_kernel_time": 0.124716, "process_mem_max_rss": "113721344", "process_in_blocks": "0", "process_out_blocks": "0"}
[0m17:30:45.138892 [debug] [MainThread]: Command `dbt init` succeeded at 17:30:45.138756 after 77.78 seconds
[0m17:30:45.139610 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1021cb260>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1050b0140>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104d55730>]}
[0m17:30:45.140186 [debug] [MainThread]: Flushing usage events
[0m17:30:56.274947 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107248a10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111918da0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111918ad0>]}


============================== 17:30:56.277001 | 853e37e8-490e-4560-8cf7-44b335714337 ==============================
[0m17:30:56.277001 [info ] [MainThread]: Running with dbt=1.8.0
[0m17:30:56.277245 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/shubhamnaik/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m17:30:56.286585 [info ] [MainThread]: dbt version: 1.8.0
[0m17:30:56.286784 [info ] [MainThread]: python version: 3.12.5
[0m17:30:56.286898 [info ] [MainThread]: python path: /usr/local/bin/python3
[0m17:30:56.287001 [info ] [MainThread]: os info: macOS-14.6.1-arm64-arm-64bit
[0m17:30:56.429042 [info ] [MainThread]: Using profiles dir at /Users/shubhamnaik/.dbt
[0m17:30:56.429251 [info ] [MainThread]: Using profiles.yml file at /Users/shubhamnaik/.dbt/profiles.yml
[0m17:30:56.429366 [info ] [MainThread]: Using dbt_project.yml file at /Users/shubhamnaik/dbt_pipeline/dbt_project.yml
[0m17:30:56.429504 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m17:30:56.430018 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_wall_clock_time": 0.18037646, "process_user_time": 0.525299, "process_kernel_time": 0.085046, "process_mem_max_rss": "114442240", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m17:30:56.430207 [debug] [MainThread]: Command `dbt debug` failed at 17:30:56.430171 after 0.18 seconds
[0m17:30:56.430330 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1118d5160>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11247f0e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111918ce0>]}
[0m17:30:56.430457 [debug] [MainThread]: Flushing usage events
[0m17:46:06.610654 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1079211f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108b90fe0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108b90d70>]}


============================== 17:46:06.612811 | 1fc69c00-2900-4935-bf4f-22151b5952b7 ==============================
[0m17:46:06.612811 [info ] [MainThread]: Running with dbt=1.8.0
[0m17:46:06.613053 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/Users/shubhamnaik/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt deps', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m17:46:06.613365 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/shubhamnaik/dbt_pipeline/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m17:46:06.614577 [debug] [MainThread]: Resource report: {"command_name": "deps", "command_wall_clock_time": 0.029178625, "process_user_time": 0.429561, "process_kernel_time": 0.077312, "process_mem_max_rss": "91586560", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m17:46:06.614838 [debug] [MainThread]: Command `dbt deps` failed at 17:46:06.614795 after 0.03 seconds
[0m17:46:06.614984 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1079211f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1085ab680>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1088ed1c0>]}
[0m17:46:06.615117 [debug] [MainThread]: Flushing usage events
